<script type="text/javascript" src="js/jquery-1.12.4.js"></script>
<script type="text/javascript" src="js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        "scrollY": 340,
        "scrollX": true
    } );
} );
</script>
<link href="css/jquery.dataTables.min.css" rel="stylesheet">
<style>
div.dataTables_wrapper {
		height: 500px;
        width: 950px;
        margin: 0 auto;
    }
</style>
<table id="example" class="table table-bordered display nowrap" style="width:100%">
<caption>PESTICIDEWISE (IMPORTED) DEMAND DURING 2013-14 TO 2015-16<br /></caption>
<thead>
<tr><td colspan="2" align="center">As on 09.11.2016
</td>
<td colspan="7" align="center">Unit:  M.T. (Tech. Grade)
</td>
</tr><tr><th>S. No.</th>
<th>Pesticides</th>
<th>Group</th>
<th>2013-14</th>
<th>2014-15</th>
<th>2015-16 (As on 09.11.2016)</th>
</tr>
</thead>
<tr><td colspan="6"><b>INSECTICIDES</b></td>
</tr><tr><td>1</td>
<td>Acetamiprid</td>
<td>i</td>
<td>3.1</td>
<td>5.1</td>
<td>6</td>
</tr><tr><td>2</td>
<td>Allethrin</td>
<td>i</td>
<td>8.8</td>
<td>8.83</td>
<td>7</td>
</tr><tr><td>3</td>
<td>Bita Cyfluthrin</td>
<td>i</td>
<td></td>
<td></td>
<td>3</td>
</tr><tr><td>4</td>
<td>Buprofezin </td>
<td>i</td>
<td></td>
<td>2</td>
<td>2</td>
</tr><tr><td>5</td>
<td>Carbaryl</td>
<td>i</td>
<td>25.9</td>
<td>24.9</td>
<td>24</td>
</tr><tr><td>6</td>
<td>Carbofuran</td>
<td>i</td>
<td>27.5</td>
<td>27.23</td>
<td>17</td>
</tr><tr><td>7</td>
<td>Carbosulfan</td>
<td>i</td>
<td>15.6</td>
<td>15.7</td>
<td>11</td>
</tr><tr><td>8</td>
<td>Cartap Hydrochloride</td>
<td>i</td>
<td>35.4</td>
<td>37.5</td>
<td>29</td>
</tr><tr><td>9</td>
<td>Chlorothalonil</td>
<td>i</td>
<td>12.5</td>
<td>12</td>
<td>12</td>
</tr><tr><td>10</td>
<td>Cyfluthrin</td>
<td>i</td>
<td></td>
<td></td>
<td>4</td>
</tr><tr><td>11</td>
<td>Cymoxanil </td>
<td>i</td>
<td>0.6</td>
<td></td>
<td></td>
</tr><tr><td>12</td>
<td>Cyphenothrin</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>13</td>
<td>Dazomet</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>14</td>
<td>Denprothrin</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>15</td>
<td>Diflubenzuron</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>16</td>
<td>Dormothion</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>17</td>
<td>D-trans Allethrin</td>
<td>i</td>
<td>5</td>
<td>4</td>
<td>2</td>
</tr><tr><td>18</td>
<td>Febubucarb (BPMC)</td>
<td>i</td>
<td>2.9</td>
<td>2</td>
<td>2</td>
</tr><tr><td>19</td>
<td>Fipronil</td>
<td>i</td>
<td>5</td>
<td>4</td>
<td>4</td>
</tr><tr><td>20</td>
<td>Flufenoxuron</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>21</td>
<td>Fluvalinate</td>
<td>i</td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>22</td>
<td>Imidachloprid</td>
<td>i</td>
<td>26.5</td>
<td>27</td>
<td>33</td>
</tr><tr><td>23</td>
<td>Lamda-cyahalothrin</td>
<td>i</td>
<td>19</td>
<td>18</td>
<td>18</td>
</tr><tr><td>24</td>
<td>Metsulfuron Methyl</td>
<td>i</td>
<td>0.24</td>
<td></td>
<td></td>
</tr><tr><td>25</td>
<td>Pendimethalene</td>
<td>i</td>
<td>0.96</td>
<td></td>
<td></td>
</tr><tr><td>26</td>
<td>Permethrin</td>
<td>i</td>
<td>5.4</td>
<td>3</td>
<td>3</td>
</tr><tr><td>27</td>
<td>Phenthoate</td>
<td>i</td>
<td>11.55</td>
<td>10</td>
<td>10</td>
</tr><tr><td>28</td>
<td>Primiphos Methyl</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>29</td>
<td>Profenophos</td>
<td>i</td>
<td>65</td>
<td>60</td>
<td>60</td>
</tr><tr><td>30</td>
<td>Propargite</td>
<td>i</td>
<td>0.9</td>
<td></td>
<td>1</td>
</tr><tr><td>31</td>
<td>Propoxur</td>
<td>i</td>
<td>3</td>
<td>3</td>
<td>5</td>
</tr><tr><td>32</td>
<td>Thiodicarb</td>
<td>i</td>
<td>2.4</td>
<td>2</td>
<td>2</td>
</tr><tr><td>33</td>
<td>Thiomethoxam</td>
<td>i</td>
<td>5.1</td>
<td>5</td>
<td>4</td>
</tr><tr><td>34</td>
<td>Transfluthrin</td>
<td>i</td>
<td></td>
<td></td>
<td>4</td>
</tr><tr><td>35</td>
<td>Trichlorofon</td>
<td>i</td>
<td>2.9</td>
<td>2</td>
<td>2</td>
</tr><tr><td>36</td>
<td>Trifluralin</td>
<td>i</td>
<td>2</td>
<td>4</td>
<td>4</td>
</tr><tr><td><b>Sub Total (Insecticide)</b></td>
<td></td>
<td></td>
<td><b>287.25</b></td>
<td><b>277.26</b></td>
<td><b>278</b></td>
</tr><tr><td colspan="6"><b>FUNGICIDES</b> </td>
</tr><tr><td>37</td>
<td>Benomyl</td>
<td>f</td>
<td>2.6</td>
<td>2</td>
<td>2</td>
</tr><tr><td>38</td>
<td>Bitertanol</td>
<td>f</td>
<td>0.3</td>
<td></td>
<td></td>
</tr><tr><td>39</td>
<td>Captafol/Difolaton</td>
<td>f</td>
<td>3</td>
<td></td>
<td></td>
</tr><tr><td>40</td>
<td>Carbendazim</td>
<td>f</td>
<td>90</td>
<td></td>
<td></td>
</tr><tr><td>41</td>
<td>Carboxin</td>
<td>f</td>
<td></td>
<td>1</td>
<td>1</td>
</tr><tr><td>42</td>
<td>Chlorthalonil</td>
<td>f</td>
<td>1.5</td>
<td></td>
<td></td>
</tr><tr><td>43</td>
<td>Copper Hydroxide</td>
<td>f</td>
<td>0.8</td>
<td></td>
<td></td>
</tr><tr><td>44</td>
<td>Copper Oxychloride</td>
<td>f</td>
<td>25</td>
<td></td>
<td></td>
</tr><tr><td>45</td>
<td>Copper Sulphate</td>
<td>f</td>
<td>20</td>
<td></td>
<td></td>
</tr><tr><td>46</td>
<td>Difencanazole</td>
<td>f</td>
<td>3</td>
<td>2</td>
<td>2</td>
</tr><tr><td>47</td>
<td>Ediphenphos</td>
<td>f</td>
<td>2.4</td>
<td>2</td>
<td>1</td>
</tr><tr><td>48</td>
<td>Fenazaquin</td>
<td>f</td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>49</td>
<td>Fosetyl-AL</td>
<td>f</td>
<td>2.1</td>
<td>2</td>
<td>2</td>
</tr><tr><td>50</td>
<td>Hexaconazole</td>
<td>f</td>
<td>11.3</td>
<td>10</td>
<td>10</td>
</tr><tr><td>51</td>
<td>Iprobenofos</td>
<td>f</td>
<td>3</td>
<td>3</td>
<td>3</td>
</tr><tr><td>52</td>
<td>Kasugamycine</td>
<td>f</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr><tr><td>53</td>
<td>Kitazine</td>
<td>f</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr><tr><td>54</td>
<td>Mancozeb</td>
<td>f</td>
<td>200</td>
<td></td>
<td></td>
</tr><tr><td>55</td>
<td>Metalaxyl</td>
<td>f</td>
<td>5.32</td>
<td>4.5</td>
<td>2</td>
</tr><tr><td>56</td>
<td>Methomyl</td>
<td>f</td>
<td>5.4</td>
<td>7</td>
<td>3</td>
</tr><tr><td>57</td>
<td>Oxycarboxin</td>
<td>f</td>
<td>1</td>
<td></td>
<td></td>
</tr><tr><td>58</td>
<td>Penconazole</td>
<td>f</td>
<td>1.45</td>
<td></td>
<td></td>
</tr><tr><td>59</td>
<td>Propiconazole</td>
<td>f</td>
<td>6.29</td>
<td>4</td>
<td>4</td>
</tr><tr><td>60</td>
<td>Propineb</td>
<td>f</td>
<td>13.4</td>
<td>12</td>
<td>12</td>
</tr><tr><td>61</td>
<td>Spinosad</td>
<td>f</td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>62</td>
<td>Sulphur (Dust &amp; WP)</td>
<td>f</td>
<td>145</td>
<td></td>
<td></td>
</tr><tr><td>63</td>
<td>Teboconazole</td>
<td>f</td>
<td>0.6</td>
<td></td>
<td></td>
</tr><tr><td>64</td>
<td>Thiophenate methyl</td>
<td>f</td>
<td>8.09</td>
<td>7</td>
<td>7</td>
</tr><tr><td>65</td>
<td>Thiram</td>
<td>f</td>
<td>10</td>
<td></td>
<td></td>
</tr><tr><td>66</td>
<td>Tricyclazole</td>
<td>f</td>
<td>19.6</td>
<td>19</td>
<td>19</td>
</tr><tr><td>67</td>
<td>Zineb</td>
<td>f</td>
<td>18</td>
<td></td>
<td></td>
</tr><tr><td>68</td>
<td>Ziram</td>
<td>f</td>
<td>2</td>
<td></td>
<td></td>
</tr><tr><td><b>Sub Total (Fungicides)</b></td>
<td></td>
<td></td>
<td><b>603.14</b></td>
<td><b>77.5</b></td>
<td><b>73</b></td>
</tr><tr><td colspan="6"><b>WEEDICIDES</b></td>
</tr><tr><td>69</td>
<td>2, 4-D</td>
<td>h</td>
<td>28</td>
<td></td>
<td></td>
</tr><tr><td>70</td>
<td>Anilophos</td>
<td>h</td>
<td>3</td>
<td></td>
<td></td>
</tr><tr><td>71</td>
<td>Atrazine</td>
<td>h</td>
<td>95</td>
<td></td>
<td></td>
</tr><tr><td>72</td>
<td>Benthiocarb</td>
<td>h</td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>73</td>
<td>Butachlor</td>
<td>h</td>
<td>69</td>
<td></td>
<td></td>
</tr><tr><td>74</td>
<td>Diazinon</td>
<td>h</td>
<td>3.8</td>
<td>3</td>
<td>3</td>
</tr><tr><td>75</td>
<td>Fluchloralin</td>
<td>h</td>
<td>4</td>
<td></td>
<td></td>
</tr><tr><td>76</td>
<td>Glyphosate</td>
<td>h</td>
<td>157</td>
<td></td>
<td></td>
</tr><tr><td>77</td>
<td>Indoxacarb</td>
<td>h</td>
<td>5.8</td>
<td>7</td>
<td>8</td>
</tr><tr><td>78</td>
<td>Linuron</td>
<td>h</td>
<td>1.5</td>
<td></td>
<td></td>
</tr><tr><td>79</td>
<td>Metribuzin</td>
<td>h</td>
<td>14.4</td>
<td></td>
<td>12</td>
</tr><tr><td>80</td>
<td>Oxadiargyl</td>
<td>h</td>
<td>3</td>
<td>2</td>
<td>3</td>
</tr><tr><td>81</td>
<td>Oxyfluorfen</td>
<td>h</td>
<td>3</td>
<td>3</td>
<td>3</td>
</tr><tr><td>82</td>
<td>Paraquat dichloride</td>
<td>h</td>
<td>23</td>
<td></td>
<td></td>
</tr><tr><td>83</td>
<td>Pretilachlor</td>
<td>h</td>
<td>31</td>
<td></td>
<td></td>
</tr><tr><td><b>Sub Total (Weedicides)</b></td>
<td></td>
<td></td>
<td><b>441.5</b></td>
<td><b>15</b></td>
<td><b>31</b></td>
</tr><tr><td colspan="6"><b>RODENTICIDES</b></td>
</tr><tr><td>84</td>
<td>Aluminium Phosphide</td>
<td>r</td>
<td>8</td>
<td></td>
<td></td>
</tr><tr><td>85</td>
<td>Bromadiolone</td>
<td>r</td>
<td>8.11</td>
<td>5</td>
<td>2</td>
</tr><tr><td>86</td>
<td>Zinc Phosphide</td>
<td>r</td>
<td>3</td>
<td></td>
<td></td>
</tr><tr><td><b>Sub Total (Rodenticides)</b></td>
<td></td>
<td></td>
<td><b>19.11</b></td>
<td><b>5</b></td>
<td><b>2</b></td>
</tr><tr><td colspan="6"><b>PLANT GROWTH REGULATOR</b></td>
</tr><tr><td>87</td>
<td>Alpha Nepthyl Acetic Acid</td>
<td> pgr</td>
<td>4</td>
<td>4</td>
<td></td>
</tr><tr><td>88</td>
<td>Gibberallic Acid</td>
<td> pgr</td>
<td>4.1</td>
<td>3.5</td>
<td></td>
</tr><tr><td>89</td>
<td>Tricontanol</td>
<td> pgr</td>
<td>1</td>
<td>1</td>
<td></td>
</tr><tr><td>90</td>
<td>Validamycin</td>
<td> pgr</td>
<td>1</td>
<td>1</td>
<td></td>
</tr><tr><td><b>Sub Total (PGR)</b></td>
<td></td>
<td></td>
<td><b>10.1</b></td>
<td><b>9.5</b></td>
<td><b>0</b></td>
</tr><tr><td>91</td>
<td>Others </td>
<td>misc</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td><b>TOTAL CHEMICAL PESTICIDES</b></td>
<td></td>
<td></td>
<td><b>1361.1</b></td>
<td><b>384.26</b></td>
<td><b>384</b></td>
</tr><tr><td colspan="6"><b>BIO-PESTICIDES</b></td>
</tr><tr><td>92</td>
<td>Azadirachin</td>
<td>bp</td>
<td></td>
<td>13</td>
<td></td>
</tr><tr><td>93</td>
<td>BacillusThurigiensis</td>
<td>bp</td>
<td>20</td>
<td>3</td>
<td></td>
</tr><tr><td>94</td>
<td>Beauveria Bassiana</td>
<td>bp</td>
<td>35</td>
<td>5</td>
<td></td>
</tr><tr><td>95</td>
<td>Metarrhizium anisopliae</td>
<td>bp</td>
<td></td>
<td>1</td>
<td></td>
</tr><tr><td>96</td>
<td>Neem based insecticides </td>
<td>bp</td>
<td>50</td>
<td></td>
<td></td>
</tr><tr><td>97</td>
<td>NPV (H)</td>
<td>bp</td>
<td>40</td>
<td></td>
<td></td>
</tr><tr><td>98</td>
<td>Pseudomonas fluorescens</td>
<td>bp</td>
<td></td>
<td>42</td>
<td></td>
</tr><tr><td>99</td>
<td>Tricoderma Spp.</td>
<td>bp</td>
<td>40</td>
<td></td>
<td></td>
</tr><tr><td>100</td>
<td>Tricoderma viridi</td>
<td>bp</td>
<td></td>
<td>75</td>
<td></td>
</tr><tr><td>101</td>
<td>Verticillium licanii</td>
<td>bp</td>
<td></td>
<td>1</td>
<td></td>
</tr><tr><td><b>SUB TOTAL (BIO-PESTICIDES)</b></td>
<td></td>
<td></td>
<td><b>185</b></td>
<td><b>140</b></td>
<td><b>0</b></td>
</tr><tr><td><b>GRAND TOTAL</b></td>
<td></td>
<td></td>
<td><b>1546</b></td>
<td><b>524</b></td>
<td><b>384</b></td>
</tr>
<tr><td colspan="6"><b>Source:</b> States/UTs, Zonal conference on inputs(PP).
</td>
</tr><tr><td colspan="6"><b>Note:-</b>h  i-  Insecticides, h– weedicides, f – Fungicides,  pgr – Plant growth regulator, bp - Biopesticide, misc- miscellaneous
</td>
</tr></table>