<script type="text/javascript" src="js/jquery-1.12.4.js"></script>
<script type="text/javascript" src="js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        "scrollY": 340,
        "scrollX": true
    } );
} );
</script>
<link href="css/jquery.dataTables.min.css" rel="stylesheet">
<style>
div.dataTables_wrapper {
		height: 500px;
        width: 950px;
        margin: 0 auto;
    }
</style>
<table id="example" class="table table-bordered display nowrap" style="width:100%">
<caption>PESTICIDEWISE CONSUMPTION OF INDIGENOUS PESTICIDES DURING 2010-11 TO 2015-16<br /></caption>
<thead>
<tr><td colspan="2" align="center">As on 09.11.2016
</td>
<td colspan="7" align="center">Unit:  M.T. (Tech. Grade)
</td>
</tr><tr><th>S. No.</th>
<th>Pesticides</th>
<th>Group
</th><th>2010-11</th>
<th>2011-12 </th>
<th>2012-13</th>
<th>2013-14</th>
<th>2014-15</th>
<th>2015-16 (As on 09.11.2016)</th>
</tr>
</thead>
<tbody>
<tr><td colspan="9"><b>INSECTICIDES</b></td>
</tr><tr><td>1</td>
<td>Acephate</td>
<td>i</td>
<td>1461</td>
<td>132</td>
<td>30</td>
<td>319</td>
<td>357</td>
<td>340</td>
</tr><tr><td>2</td>
<td>Acetamiprid</td>
<td>i</td>
<td>63</td>
<td>2</td>
<td>4</td>
<td>46</td>
<td>52</td>
<td>63</td>
</tr><tr><td>3</td>
<td>Aldicarb</td>
<td>i</td>
<td>5</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>4</td>
<td>Allethrin</td>
<td>i</td>
<td>0.1</td>
<td>1</td>
<td>6</td>
<td>3</td>
<td>3</td>
<td>4</td>
</tr><tr><td>5</td>
<td>Alpha Cypermethrin</td>
<td>i</td>
<td>130</td>
<td>9</td>
<td>8</td>
<td>30</td>
<td>28</td>
<td>22</td>
</tr><tr><td>6</td>
<td>Alphamethrin</td>
<td>i</td>
<td>150</td>
<td></td>
<td>0.6</td>
<td>1</td>
<td>1</td>
<td>0.04</td>
</tr><tr><td>7</td>
<td>BHC</td>
<td>i</td>
<td>0.29</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>8</td>
<td>Bifenthrin</td>
<td>i</td>
<td></td>
<td></td>
<td>2</td>
<td>4</td>
<td>42</td>
<td>2</td>
</tr><tr><td>9</td>
<td>Buprofezin </td>
<td>i</td>
<td></td>
<td>6</td>
<td>9</td>
<td>9</td>
<td>18</td>
<td>16</td>
</tr><tr><td>10</td>
<td>Carbaryl</td>
<td>i</td>
<td>140</td>
<td>5</td>
<td>6</td>
<td>52</td>
<td>48</td>
<td>48</td>
</tr><tr><td>11</td>
<td>Carbofuran</td>
<td>i</td>
<td></td>
<td>2292</td>
<td>235</td>
<td>370</td>
<td>359</td>
<td>339</td>
</tr><tr><td>12</td>
<td>Carbosulfan</td>
<td>i</td>
<td>15</td>
<td>46</td>
<td>49</td>
<td>48</td>
<td>87</td>
<td>44</td>
</tr><tr><td>13</td>
<td>Cartap Hydrochloride</td>
<td>i</td>
<td>1678</td>
<td>1638</td>
<td>231</td>
<td>293</td>
<td>371</td>
<td>267</td>
</tr><tr><td>14</td>
<td>Chlorantraniliprole</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td>30</td>
<td>73</td>
<td>5</td>
</tr><tr><td>15</td>
<td>Chlorfenapyr</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
</tr><tr><td>16</td>
<td>Chlorfenvinphos</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>493</td>
<td></td>
</tr><tr><td>17</td>
<td>Chloroantipola</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>18</td>
<td>Chlorothalonil</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>19</td>
<td>Chlorpyriphos</td>
<td>i</td>
<td>3133</td>
<td>464</td>
<td>183</td>
<td>4412</td>
<td></td>
<td>502</td>
</tr><tr><td>20</td>
<td>Chlorpyriphos Methyl</td>
<td>i</td>
<td></td>
<td>301</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>21</td>
<td>Chlorpyriphos+Cyphermetherin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>5</td>
<td>1</td>
</tr><tr><td>22</td>
<td>Clothianidin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
</tr><tr><td>23</td>
<td>Cyfluthrin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>24</td>
<td>Cymoxanil </td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>2</td>
<td>2</td>
</tr><tr><td>25</td>
<td>Cypermethrin</td>
<td>i</td>
<td>2167</td>
<td>81</td>
<td>59</td>
<td>261</td>
<td>246</td>
<td>295</td>
</tr><tr><td>26</td>
<td>Cyphenothrin</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>27</td>
<td>Cyphermethrin+Chlorpyriphos</td>
<td>i</td>
<td></td>
<td></td>
<td>3</td>
<td>2</td>
<td></td>
<td></td>
</tr><tr><td>28</td>
<td>DDVP</td>
<td>i</td>
<td>200</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>29</td>
<td>Decamethrin</td>
<td>i</td>
<td></td>
<td></td>
<td>4</td>
<td></td>
<td>19</td>
<td>20</td>
</tr><tr><td>30</td>
<td>Deltamethrin</td>
<td>i</td>
<td>80</td>
<td>10</td>
<td></td>
<td>20</td>
<td></td>
<td></td>
</tr><tr><td>31</td>
<td>Deltamethrin+Triazophos</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>0.05</td>
</tr><tr><td>32</td>
<td>Dichlorvos</td>
<td>i</td>
<td>693</td>
<td>347</td>
<td>258</td>
<td>428</td>
<td>414</td>
<td>406</td>
</tr><tr><td>33</td>
<td>Dicofol</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>10</td>
</tr><tr><td>34</td>
<td>Difenthiuron</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td>0.15</td>
<td>0.15</td>
<td>2</td>
</tr><tr><td>35</td>
<td>Diflubenzuron</td>
<td>i</td>
<td></td>
<td></td>
<td>0.05</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>36</td>
<td>Dimethoate</td>
<td>i</td>
<td>536</td>
<td>193</td>
<td>112</td>
<td>243</td>
<td>208</td>
<td>204</td>
</tr><tr><td>37</td>
<td>D-trans Allethrin</td>
<td>i</td>
<td></td>
<td></td>
<td>7</td>
<td>5</td>
<td>4</td>
<td>5</td>
</tr><tr><td>38</td>
<td>Emamection Benzoate</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
<td>30</td>
<td>47</td>
<td>47</td>
</tr><tr><td>39</td>
<td>Endosulfan</td>
<td>i</td>
<td>2857</td>
<td>197</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>40</td>
<td>Ethephon</td>
<td>i</td>
<td>6</td>
<td>1.49</td>
<td>5</td>
<td>6</td>
<td>14</td>
<td>17</td>
</tr><tr><td>41</td>
<td>Ethion</td>
<td>i</td>
<td>141</td>
<td>15</td>
<td>4</td>
<td>30</td>
<td>20</td>
<td>28</td>
</tr><tr><td>42</td>
<td>Ethiprole</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>43</td>
<td>Ethofenprox</td>
<td>i</td>
<td></td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr><tr><td>44</td>
<td>Febubucarb (BPMC)</td>
<td>i</td>
<td></td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>3</td>
<td>3</td>
</tr><tr><td>45</td>
<td>Fenarimol</td>
<td>i</td>
<td></td>
<td>0.25</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>46</td>
<td>Fenitrothion</td>
<td>i</td>
<td>120</td>
<td>0.11</td>
<td></td>
<td></td>
<td></td>
<td>3</td>
</tr><tr><td>47</td>
<td>Fenpropathrin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>48</td>
<td>Fenthion</td>
<td>i</td>
<td>14</td>
<td>0.1</td>
<td></td>
<td>3</td>
<td>5</td>
<td>8</td>
</tr><tr><td>49</td>
<td>Fenvalerate</td>
<td>i</td>
<td>591</td>
<td>583</td>
<td>98</td>
<td>201</td>
<td>215</td>
<td>231</td>
</tr><tr><td>50</td>
<td>Fipronil</td>
<td>i</td>
<td></td>
<td>172</td>
<td>260</td>
<td>338</td>
<td>431</td>
<td>430</td>
</tr><tr><td>51</td>
<td>Flubendiamide</td>
<td>i</td>
<td>4</td>
<td></td>
<td></td>
<td>0.06</td>
<td>3</td>
<td>3</td>
</tr><tr><td>52</td>
<td>Fluvalinate</td>
<td>i</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>53</td>
<td>Imidachloprid</td>
<td>i</td>
<td>429</td>
<td>148</td>
<td>139</td>
<td>239</td>
<td>297</td>
<td>308</td>
</tr><tr><td>54</td>
<td>Imiprothrin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
</tr><tr><td>55</td>
<td>Indoxacarb</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>55</td>
</tr><tr><td>56</td>
<td>Indoxacarb</td>
<td>i</td>
<td></td>
<td>2</td>
<td>2</td>
<td>22</td>
<td>55</td>
<td></td>
</tr><tr><td>57</td>
<td>Lamda-cyahalothrin</td>
<td>i</td>
<td></td>
<td>258</td>
<td>43</td>
<td>75</td>
<td>129</td>
<td>139</td>
</tr><tr><td>58</td>
<td>Lindane</td>
<td>i</td>
<td>314</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td>0.2</td>
</tr><tr><td>59</td>
<td>Malathion</td>
<td>i</td>
<td>3571</td>
<td>1213</td>
<td>498</td>
<td>626</td>
<td>550</td>
<td>668</td>
</tr><tr><td>60</td>
<td>Metal-dehyde</td>
<td>i</td>
<td>7</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>61</td>
<td>Methomyl</td>
<td>i</td>
<td>20</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>62</td>
<td>Methyl Parathion</td>
<td>i</td>
<td>1406</td>
<td>837</td>
<td>716</td>
<td>937</td>
<td>795</td>
<td>714</td>
</tr><tr><td>63</td>
<td>Metsulfuron Methyl</td>
<td>i</td>
<td>27</td>
<td>4</td>
<td>50</td>
<td>46</td>
<td>59</td>
<td>147</td>
</tr><tr><td>64</td>
<td>Monocrotophos</td>
<td>i</td>
<td>1507</td>
<td>416</td>
<td>236</td>
<td>495</td>
<td>323</td>
<td>420</td>
</tr><tr><td>65</td>
<td>Myclobutanil</td>
<td>i</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>4</td>
</tr><tr><td>66</td>
<td>Neem based insecticides</td>
<td>i</td>
<td>225</td>
<td>65</td>
<td>4</td>
<td>64</td>
<td>15</td>
<td>15</td>
</tr><tr><td>67</td>
<td>Oxydemeton methyl</td>
<td>i</td>
<td>79</td>
<td>43</td>
<td>8</td>
<td>25</td>
<td>15</td>
<td>10</td>
</tr><tr><td>68</td>
<td>Permethrin</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>69</td>
<td>Phenthoate</td>
<td>i</td>
<td></td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>1</td>
<td>1</td>
</tr><tr><td>70</td>
<td>Phorate</td>
<td>i</td>
<td>1156</td>
<td>394</td>
<td>237</td>
<td>547</td>
<td>489</td>
<td>432</td>
</tr><tr><td>71</td>
<td>Phosalone</td>
<td>i</td>
<td>75</td>
<td>15</td>
<td>0.05</td>
<td>12</td>
<td>2</td>
<td>6</td>
</tr><tr><td>72</td>
<td>Phosphamidon</td>
<td>i</td>
<td>199</td>
<td>88</td>
<td>64</td>
<td>112</td>
<td>100</td>
<td>95</td>
</tr><tr><td>73</td>
<td>Prallethrin</td>
<td>i</td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>74</td>
<td>Primiphosmethyl</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>75</td>
<td>Profenofos + Cypermethrin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>0.49</td>
</tr><tr><td>76</td>
<td>Profenophos</td>
<td>i</td>
<td></td>
<td>48</td>
<td>46</td>
<td>137</td>
<td>320</td>
<td>334</td>
</tr><tr><td>77</td>
<td>Propargite</td>
<td>i</td>
<td></td>
<td>2</td>
<td>19</td>
<td>16</td>
<td>14</td>
<td>14</td>
</tr><tr><td>78</td>
<td>Pyrethrum</td>
<td>i</td>
<td>8</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>4</td>
</tr><tr><td>79</td>
<td>Quinalphos</td>
<td>i</td>
<td>1063</td>
<td>457</td>
<td>346</td>
<td>569</td>
<td>563</td>
<td>533</td>
</tr><tr><td>80</td>
<td>Spinosad</td>
<td>i</td>
<td>93</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>81</td>
<td>Temephos</td>
<td>i</td>
<td>52</td>
<td></td>
<td></td>
<td>12</td>
<td>5</td>
<td>5</td>
</tr><tr><td>82</td>
<td>Thiacloprid</td>
<td>i</td>
<td></td>
<td>2</td>
<td>1</td>
<td></td>
<td>2</td>
<td>2</td>
</tr><tr><td>83</td>
<td>Thiodicarb</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
</tr><tr><td>84</td>
<td>Thiomethoxam</td>
<td>i</td>
<td></td>
<td>2</td>
<td>2</td>
<td>18</td>
<td>46</td>
<td>54</td>
</tr><tr><td>85</td>
<td>Transfluthrin</td>
<td>i</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>86</td>
<td>Triazophos</td>
<td>i</td>
<td>1109</td>
<td>111</td>
<td>25</td>
<td>226</td>
<td>338</td>
<td>307</td>
</tr><tr><td><b>Sub Total (Insecticide)</b></td>
<td></td>
<td></td>
<td><b>25526</b></td>
<td><b>10611</b></td>
<td><b>4027</b></td>
<td><b>11367</b></td>
<td><b>7694</b></td>
<td><b>7652</b></td>
</tr><tr><td colspan="9"><b>FUNGICIDES </b></td>
</tr><tr><td>87</td>
<td>Aureofungin</td>
<td>f</td>
<td>3</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>88</td>
<td>Azoxystrobin</td>
<td>f</td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td>2</td>
<td>3</td>
</tr><tr><td>89</td>
<td>Benomyl</td>
<td>f</td>
<td></td>
<td>2</td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
</tr><tr><td>90</td>
<td>Bispyribac Sodium</td>
<td>f</td>
<td></td>
<td>11</td>
<td>11</td>
<td>0.07</td>
<td>28</td>
<td>47</td>
</tr><tr><td>91</td>
<td>Bitertanol</td>
<td>f</td>
<td></td>
<td>3</td>
<td>0.81</td>
<td></td>
<td>0.92</td>
<td>0.93</td>
</tr><tr><td>92</td>
<td>Captafol/Difolaton</td>
<td>f</td>
<td>7</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>93</td>
<td>Captan</td>
<td>f</td>
<td>220</td>
<td>47</td>
<td>44</td>
<td>79</td>
<td>58</td>
<td>58</td>
</tr><tr><td>94</td>
<td>Captan+Hexaconazole</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>16</td>
</tr><tr><td>95</td>
<td>Carbendazim</td>
<td>f</td>
<td>988</td>
<td>645</td>
<td>371</td>
<td>552</td>
<td>493</td>
<td>587</td>
</tr><tr><td>96</td>
<td>Carbendazim+Mancozeb</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>25</td>
</tr><tr><td>97</td>
<td>Carboxin</td>
<td>f</td>
<td></td>
<td>4</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>3</td>
</tr><tr><td>98</td>
<td>Chlorthalonil</td>
<td>f</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>99</td>
<td>Copper Hydroxide</td>
<td>f</td>
<td>15</td>
<td></td>
<td>1</td>
<td>1</td>
<td>9</td>
<td>6</td>
</tr><tr><td>100</td>
<td>Copper Oxychloride</td>
<td>f</td>
<td>685</td>
<td>718</td>
<td>282</td>
<td>369</td>
<td>390</td>
<td>425</td>
</tr><tr><td>101</td>
<td>Copper Sulphate</td>
<td>f</td>
<td>1327</td>
<td>293</td>
<td>266</td>
<td>251</td>
<td>150</td>
<td>173</td>
</tr><tr><td>102</td>
<td>Cuprous oxide</td>
<td>f</td>
<td>6</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>4</td>
</tr><tr><td>103</td>
<td>Cyhalofop-N-Butyl</td>
<td>f</td>
<td>0.01</td>
<td>0.01</td>
<td>0.05</td>
<td>0.002</td>
<td>0.86</td>
<td>0.86</td>
</tr><tr><td>104</td>
<td>Dicofol</td>
<td>f</td>
<td>66</td>
<td>6</td>
<td>5</td>
<td>26</td>
<td>13</td>
<td></td>
</tr><tr><td>105</td>
<td>Difencanazole</td>
<td>f</td>
<td></td>
<td>0.86</td>
<td>0.96</td>
<td>1</td>
<td>1</td>
<td>3</td>
</tr><tr><td>106</td>
<td>Dimethomorph</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>0.02</td>
</tr><tr><td>107</td>
<td>Dinocap</td>
<td>f</td>
<td>0.21</td>
<td>7</td>
<td>5</td>
<td>5</td>
<td>3</td>
<td>4</td>
</tr><tr><td>108</td>
<td>Ediphenphos</td>
<td>f</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>109</td>
<td>Fenarimol</td>
<td>f</td>
<td></td>
<td></td>
<td>0.27</td>
<td></td>
<td>0.45</td>
<td>0.46</td>
</tr><tr><td>110</td>
<td>Fenazaquin</td>
<td>f</td>
<td>0.59</td>
<td>0.59</td>
<td>0.65</td>
<td></td>
<td>0.62</td>
<td>1</td>
</tr><tr><td>111</td>
<td>Fenoxaprop-P- Ethyle</td>
<td>f</td>
<td>8</td>
<td>1</td>
<td>1</td>
<td></td>
<td>2</td>
<td>2</td>
</tr><tr><td>112</td>
<td>Flusilazole</td>
<td>f</td>
<td></td>
<td></td>
<td>1</td>
<td>3</td>
<td>2</td>
<td>4</td>
</tr><tr><td>113</td>
<td>Fosetyl-AL</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
</tr><tr><td>114</td>
<td>Hexaconazole</td>
<td>f</td>
<td>218</td>
<td>24</td>
<td>36</td>
<td>117</td>
<td>214</td>
<td>220</td>
</tr><tr><td>115</td>
<td>Hexythiazox</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>0.5</td>
</tr><tr><td>116</td>
<td>Iprobenofos</td>
<td>f</td>
<td></td>
<td>2</td>
<td></td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr><tr><td>117</td>
<td>Isoprothiolane</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>118</td>
<td>Kasugamycine</td>
<td>f</td>
<td></td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>3</td>
<td>3</td>
</tr><tr><td>119</td>
<td>Kitazine</td>
<td>f</td>
<td></td>
<td>0.12</td>
<td>0.12</td>
<td>0.37</td>
<td>0.54</td>
<td>0.54</td>
</tr><tr><td>120</td>
<td>Lime sulphur</td>
<td>f</td>
<td>58</td>
<td></td>
<td>2</td>
<td>26</td>
<td>23</td>
<td>19</td>
</tr><tr><td>121</td>
<td>Mancozeb</td>
<td>f</td>
<td>2667</td>
<td>2015</td>
<td>1919</td>
<td>2377</td>
<td>2202</td>
<td>2193</td>
</tr><tr><td>122</td>
<td>Mancozeb+Carbendazim</td>
<td>f</td>
<td>29</td>
<td>180</td>
<td>18</td>
<td>13</td>
<td>15</td>
<td>18</td>
</tr><tr><td>123</td>
<td>Mancozeb+Metalaxyl</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td>1</td>
</tr><tr><td>124</td>
<td>MEMC</td>
<td>f</td>
<td></td>
<td></td>
<td>5</td>
<td>6</td>
<td>2</td>
<td>2</td>
</tr><tr><td>125</td>
<td>MEMC+EMC</td>
<td>f</td>
<td>6</td>
<td>23</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>126</td>
<td>Metalaxyl</td>
<td>f</td>
<td>3</td>
<td>4</td>
<td>9</td>
<td>9</td>
<td>9</td>
<td>9</td>
</tr><tr><td>127</td>
<td>Metalaxyl+Mancozeb</td>
<td>f</td>
<td>0</td>
<td>150</td>
<td>0</td>
<td>3</td>
<td>0.17</td>
<td>0.6</td>
</tr><tr><td>128</td>
<td>Methomyl</td>
<td>f</td>
<td></td>
<td>2</td>
<td>2</td>
<td>1</td>
<td>3</td>
<td>3</td>
</tr><tr><td>129</td>
<td>Metiram</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
</tr><tr><td>130</td>
<td>Metiram+Pyraclostrobin</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>3</td>
</tr><tr><td>131</td>
<td>Metribuzin</td>
<td>f</td>
<td>7</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>132</td>
<td>Nickel Chloride</td>
<td>f</td>
<td>3</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>133</td>
<td>Novaluron</td>
<td>f</td>
<td></td>
<td>4</td>
<td>2</td>
<td>1</td>
<td></td>
<td>9</td>
</tr><tr><td>134</td>
<td>Penconazole</td>
<td>f</td>
<td>0.58</td>
<td>5</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>135</td>
<td>Pencycuron</td>
<td>f</td>
<td></td>
<td></td>
<td>6</td>
<td>4</td>
<td>8</td>
<td>8</td>
</tr><tr><td>136</td>
<td>Propaquizafop</td>
<td>f</td>
<td></td>
<td></td>
<td>0.05</td>
<td></td>
<td></td>
<td>0.05</td>
</tr><tr><td>137</td>
<td>Propiconazole</td>
<td>f</td>
<td></td>
<td></td>
<td>10</td>
<td>31</td>
<td>42</td>
<td>95</td>
</tr><tr><td>138</td>
<td>Propineb</td>
<td>f</td>
<td>4</td>
<td>1</td>
<td>22</td>
<td></td>
<td>47</td>
<td>103</td>
</tr><tr><td>139</td>
<td>Pyraclostrobin</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>19</td>
<td></td>
<td></td>
</tr><tr><td>140</td>
<td>Pyrazosulfaron</td>
<td>f</td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>141</td>
<td>Pyrazosulfaron ethyl</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>20</td>
<td>56</td>
</tr><tr><td>142</td>
<td>Quizalofop-P-Ethyl</td>
<td>f</td>
<td></td>
<td></td>
<td>2</td>
<td>8</td>
<td>12</td>
<td>14</td>
</tr><tr><td>143</td>
<td>Spinosad</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>144</td>
<td>Spiromesifen</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>145</td>
<td>Streptocycline</td>
<td>f</td>
<td>33</td>
<td></td>
<td>0.1</td>
<td>3</td>
<td>0.1</td>
<td></td>
</tr><tr><td>146</td>
<td>Streptomycin+Tetracyclene</td>
<td>f</td>
<td></td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
</tr><tr><td>147</td>
<td>Sulfosulfuron</td>
<td>f</td>
<td>5</td>
<td>27</td>
<td>78</td>
<td>80</td>
<td>91</td>
<td>191</td>
</tr><tr><td>148</td>
<td>Sulphur (Dust &amp; WP)</td>
<td>f</td>
<td>2366</td>
<td>899</td>
<td>774</td>
<td>949</td>
<td>1380</td>
<td>1649</td>
</tr><tr><td>149</td>
<td>Teboconazole</td>
<td>f</td>
<td></td>
<td>7</td>
<td>4</td>
<td>2</td>
<td>4</td>
<td>4</td>
</tr><tr><td>150</td>
<td>Thiophanate-Methyle</td>
<td>f</td>
<td>0.48</td>
<td>32</td>
<td>25</td>
<td>30</td>
<td>37</td>
<td>53</td>
</tr><tr><td>151</td>
<td>Thiram</td>
<td>f</td>
<td>200</td>
<td>219</td>
<td>210</td>
<td>258</td>
<td>259</td>
<td>278</td>
</tr><tr><td>152</td>
<td>Tricyclazole</td>
<td>f</td>
<td>10</td>
<td>2</td>
<td>4</td>
<td>7</td>
<td>7</td>
<td>5</td>
</tr><tr><td>153</td>
<td>Tridemorph</td>
<td>f</td>
<td>49</td>
<td>24</td>
<td>3</td>
<td>6</td>
<td>4</td>
<td>4</td>
</tr><tr><td>154</td>
<td>Trifloxystrobin</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>155</td>
<td>Zineb</td>
<td>f</td>
<td>166</td>
<td>312</td>
<td>303</td>
<td>332</td>
<td>304</td>
<td>358</td>
</tr><tr><td>156</td>
<td>Ziram</td>
<td>f</td>
<td>127</td>
<td>77</td>
<td>70</td>
<td>82</td>
<td>66</td>
<td>93</td>
</tr><tr><td><b>Sub Total (Fungicides)</b></td>
<td></td>
<td></td>
<td><b>9275</b></td>
<td><b>5759</b></td>
<td><b>4504</b></td>
<td><b>5660</b></td>
<td><b>5917</b></td>
<td><b>6768</b></td>
</tr><tr><td colspan="9"><b>WEEDICIDES</b></td>
</tr><tr><td>157</td>
<td>2,4-D Amine Salt</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>3</td>
</tr><tr><td>158</td>
<td>2,4-D Dichlorophenoxy Acetic Acid</td>
<td>h</td>
<td>429</td>
<td>319</td>
<td>489</td>
<td>535</td>
<td>1084</td>
<td>779</td>
</tr><tr><td>159</td>
<td>2,4-D Ethyl Ester</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>8</td>
</tr><tr><td>160</td>
<td>2,4-D Sodium Salt</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>17</td>
</tr><tr><td>161</td>
<td>Alachlor</td>
<td>h</td>
<td>124</td>
<td>20</td>
<td>1</td>
<td>12</td>
<td>16</td>
<td>15</td>
</tr><tr><td>162</td>
<td>Anilophos</td>
<td>h</td>
<td>1394</td>
<td>95</td>
<td>90</td>
<td>113</td>
<td>95</td>
<td>107</td>
</tr><tr><td>163</td>
<td>Atrazine</td>
<td>h</td>
<td>318</td>
<td>149</td>
<td>68</td>
<td>107</td>
<td>178</td>
<td>282</td>
</tr><tr><td>164</td>
<td>Bensulfuron</td>
<td>h</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>165</td>
<td>Bensulfuron+Pretilachlor</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>16</td>
</tr><tr><td>166</td>
<td>Butachlor</td>
<td>h</td>
<td>2421</td>
<td>832</td>
<td>752</td>
<td>1178</td>
<td>892</td>
<td>760</td>
</tr><tr><td>167</td>
<td>Carfentrazone Ethyle</td>
<td>h</td>
<td></td>
<td>2</td>
<td>1</td>
<td>1</td>
<td></td>
<td>1</td>
</tr><tr><td>168</td>
<td>Chlodinafop-propargyl</td>
<td>h</td>
<td></td>
<td>5</td>
<td>47</td>
<td>55</td>
<td>45</td>
<td>109</td>
</tr><tr><td>169</td>
<td>Chlorimuron ethyl</td>
<td>h</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>170</td>
<td>Clomazone</td>
<td>h</td>
<td></td>
<td></td>
<td>3</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr><tr><td>171</td>
<td>Dalapon</td>
<td>h</td>
<td>3</td>
<td>0.7</td>
<td></td>
<td></td>
<td></td>
<td>0.6</td>
</tr><tr><td>172</td>
<td>Diuron</td>
<td>h</td>
<td>316</td>
<td>2</td>
<td>0.05</td>
<td>2</td>
<td>26</td>
<td>26</td>
</tr><tr><td>173</td>
<td>Dodine</td>
<td>h</td>
<td></td>
<td>66</td>
<td>73</td>
<td>80</td>
<td>85</td>
<td>92</td>
</tr><tr><td>174</td>
<td>Ethoxysulfuron</td>
<td>h</td>
<td></td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr><tr><td>175</td>
<td>Fluchloralin</td>
<td>h</td>
<td>49</td>
<td>13</td>
<td>5</td>
<td>4</td>
<td>3</td>
<td>9</td>
</tr><tr><td>176</td>
<td>Glyphosate</td>
<td>h</td>
<td>1000</td>
<td>889</td>
<td>10987</td>
<td>336</td>
<td>631</td>
<td>522</td>
</tr><tr><td>177</td>
<td>Imazamox</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>178</td>
<td>Imazathatyr</td>
<td>h</td>
<td></td>
<td>2</td>
<td>8</td>
<td>10</td>
<td>57</td>
<td>58</td>
</tr><tr><td>179</td>
<td>Isoproturon</td>
<td>h</td>
<td>842</td>
<td>744</td>
<td>710</td>
<td>728</td>
<td>622</td>
<td>102</td>
</tr><tr><td>180</td>
<td>Linuron</td>
<td>h</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>181</td>
<td>Metalachlor</td>
<td>h</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>182</td>
<td>Metribuzin</td>
<td>h</td>
<td></td>
<td>91</td>
<td>86</td>
<td>89</td>
<td>100</td>
<td>98</td>
</tr><tr><td>183</td>
<td>Oxadiargyl</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td>2</td>
</tr><tr><td>184</td>
<td>Oxyfluorfen</td>
<td>h</td>
<td>0.01</td>
<td>9</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>5</td>
</tr><tr><td>185</td>
<td>Paraquat dichloride</td>
<td>h</td>
<td>131</td>
<td>622</td>
<td>29</td>
<td>139</td>
<td>200</td>
<td>82</td>
</tr><tr><td>186</td>
<td>Pendimethalene</td>
<td>h</td>
<td></td>
<td></td>
<td>56</td>
<td>83</td>
<td>247</td>
<td></td>
</tr><tr><td>187</td>
<td>Pendimethalin</td>
<td>h</td>
<td>4</td>
<td>40</td>
<td></td>
<td></td>
<td></td>
<td>168</td>
</tr><tr><td>188</td>
<td>Pretilachlor</td>
<td>h</td>
<td>154</td>
<td>81</td>
<td>101</td>
<td>111</td>
<td>254</td>
<td>348</td>
</tr><tr><td>189</td>
<td>Propanil</td>
<td>h</td>
<td>13</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
</tr><tr><td>190</td>
<td>Simazine</td>
<td>h</td>
<td></td>
<td>0.5</td>
<td></td>
<td></td>
<td></td>
<td>0.2</td>
</tr><tr><td><b>Sub Total (Weedicides)</b></td>
<td></td>
<td></td>
<td><b>7198</b></td>
<td><b>3989</b></td>
<td><b>13515</b></td>
<td><b>3592</b></td>
<td><b>4552</b></td>
<td><b>3620</b></td>
</tr><tr><td colspan="9"><b>RODENTICIDES</b></td>
</tr><tr><td>191</td>
<td>Aluminium Phosphide</td>
<td>r</td>
<td>36</td>
<td>100</td>
<td>82</td>
<td>106</td>
<td>112</td>
<td>130</td>
</tr><tr><td>192</td>
<td>Barium Carbonate</td>
<td>r</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>4</td>
</tr><tr><td>193</td>
<td>Bromadiolone</td>
<td>r</td>
<td>3</td>
<td>3</td>
<td>2</td>
<td>9</td>
<td>9</td>
<td>8</td>
</tr><tr><td>194</td>
<td>Coumachlor</td>
<td>r</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>5</td>
</tr><tr><td>195</td>
<td>EDCT Mixture</td>
<td>r</td>
<td>2</td>
<td></td>
<td>1</td>
<td>3</td>
<td>3</td>
<td>8</td>
</tr><tr><td>196</td>
<td>Ethylene Dibromide</td>
<td>r</td>
<td>5</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>16</td>
</tr><tr><td>197</td>
<td>Methyl Bromide</td>
<td>r</td>
<td>17</td>
<td></td>
<td></td>
<td>6</td>
<td>10</td>
<td>12</td>
</tr><tr><td>198</td>
<td>Warfarin</td>
<td>r</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>199</td>
<td>Zinc Phosphide</td>
<td>r</td>
<td>96</td>
<td>110</td>
<td>83</td>
<td>124</td>
<td>107</td>
<td>121</td>
</tr><tr><td><b>Sub Total (Rodenticides)<br /></b></td>
<td></td>
<td></td>
<td><b>163<br /></b></td>
<td><b>212<br /></b></td>
<td><b>169<br /></b></td>
<td><b>248<br /></b></td>
<td><b>242<br /></b></td>
<td><b>304<br /></b></td>
</tr><tr><td colspan="9"><b>PLANT GROWTH REGULATOR<br /></b></td>
</tr><tr><td>200</td>
<td>Alpha Nepthyl Acetic Acid</td>
<td> pgr</td>
<td>29</td>
<td>10</td>
<td>7</td>
<td>14</td>
<td>14</td>
<td>18</td>
</tr><tr><td>201</td>
<td>Chlormequat Chloride</td>
<td> pgr</td>
<td>11</td>
<td></td>
<td>2</td>
<td>4</td>
<td>4</td>
<td>5</td>
</tr><tr><td>202</td>
<td>Gibberallic Acid</td>
<td> pgr</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>1</td>
<td>1</td>
<td>3</td>
</tr><tr><td>203</td>
<td>Tricontanol</td>
<td> pgr</td>
<td></td>
<td>3</td>
<td>12</td>
<td>9</td>
<td>10</td>
<td>12</td>
</tr><tr><td>204</td>
<td>Validamycin</td>
<td> pgr</td>
<td></td>
<td>3</td>
<td>3</td>
<td>2</td>
<td>2</td>
<td>3</td>
</tr><tr><td><b>Sub Total (PGR)</b></td>
<td></td>
<td></td>
<td><b>41</b></td>
<td><b>17</b></td>
<td><b>26</b></td>
<td><b>31</b></td>
<td><b>31</b></td>
<td><b>41</b></td>
</tr><tr><td>205</td>
<td>Other Chemical Pesticides</td>
<td>misc</td>
<td>520</td>
<td></td>
<td>0.42</td>
<td>0.58</td>
<td></td>
<td>101</td>
</tr><tr><td><b>TOTAL CHEMICAL PESTICIDES</b></td>
<td></td>
<td></td>
<td><b>42724</b></td>
<td><b>20588</b></td>
<td><b>22241</b></td>
<td><b>20899</b></td>
<td><b>18436</b></td>
<td><b>18484</b></td>
</tr><tr><td><b>BIO-PESTICIDES</b></td>
</tr><tr><td>206</td>
<td>Azadirachin</td>
<td>bp</td>
<td>80</td>
<td>176</td>
<td>0.79</td>
<td>68</td>
<td>302</td>
<td>128</td>
</tr><tr><td>207</td>
<td>BacillusThurigiensis</td>
<td>bp</td>
<td>121</td>
<td>13</td>
<td>3</td>
<td>81</td>
<td>136</td>
<td>152</td>
</tr><tr><td>208</td>
<td>Beauveria Bassiana</td>
<td>bp</td>
<td>40</td>
<td>642</td>
<td>65</td>
<td>780</td>
<td>848</td>
<td>953</td>
</tr><tr><td>209</td>
<td>Metarrhizium anisopliae</td>
<td>bp</td>
<td></td>
<td>150</td>
<td>2</td>
<td>121</td>
<td>118</td>
<td>120</td>
</tr><tr><td>210</td>
<td>Neem based insecticides </td>
<td>bp</td>
<td>492</td>
<td>3515</td>
<td>569</td>
<td>488</td>
<td>594</td>
<td>1032</td>
</tr><tr><td>211</td>
<td>NPV (H)</td>
<td>bp</td>
<td>141</td>
<td>51</td>
<td>1</td>
<td>20</td>
<td>124</td>
<td>47</td>
</tr><tr><td>212</td>
<td>NPV (S)</td>
<td>bp</td>
<td></td>
<td>0.37</td>
<td>0.51</td>
<td>24</td>
<td>0.43</td>
<td>174</td>
</tr><tr><td>213</td>
<td>Pascilomysis</td>
<td>bp</td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>55</td>
<td>55</td>
</tr><tr><td>214</td>
<td>Photorhabdus</td>
<td>bp</td>
<td></td>
<td>10</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>215</td>
<td>Pseudomonas fluorescens</td>
<td>bp</td>
<td>775</td>
<td>388</td>
<td>206</td>
<td>682</td>
<td>738</td>
<td>998</td>
</tr><tr><td>216</td>
<td>Tricoderma Harzianum</td>
<td>bp</td>
<td>1224</td>
<td>5</td>
<td>9</td>
<td>10</td>
<td>14</td>
<td>22</td>
</tr><tr><td>217</td>
<td>Tricoderma Spp.</td>
<td>bp</td>
<td></td>
<td></td>
<td>0.36</td>
<td>913</td>
<td>1255</td>
<td>22</td>
</tr><tr><td>218</td>
<td>Tricoderma viridi</td>
<td>bp</td>
<td></td>
<td>1837</td>
<td>284</td>
<td>208</td>
<td>4235</td>
<td>1700</td>
</tr><tr><td>219</td>
<td>Verticillium licanii</td>
<td>bp</td>
<td>40</td>
<td>490</td>
<td>35</td>
<td>545</td>
<td>714</td>
<td>695</td>
</tr><tr><td>220</td>
<td>Other Bio-pesticides</td>
<td>bp</td>
<td></td>
<td></td>
<td>2</td>
<td>3</td>
<td></td>
<td></td>
</tr><tr><td><b>SUB TOTAL (BIO-PESTICIDES)<br /></b></td>
<td></td>
<td>2914</td>
<td>7278</td>
<td>1178</td>
<td>3944</td>
<td>9132</td>
<td>6098</td>
</tr><tr><td><b>GRAND TOTAL:<br /></b></td>
<td></td>
<td>45637</td>
<td>27865</td>
<td>23419</td>
<td>24843</td>
<td>27569</td>
<td>24582</td>
</tr>
</tbody>
<tr><td colspan="9"><b>Source :</b>States /UTs, Zonal Conference on inputs(PP).</td>
</tr><td colspan="9"><b>Note:  i =</b>  i = insecticides f = fungicides h = herbicides r = rodenticide  pg = plant growth regulator bp = biopesticides, other=misc </td>
</table>