<script type="text/javascript" src="js/jquery-1.12.4.js"></script>
<script type="text/javascript" src="js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        "scrollY": 340,
        "scrollX": true
    } );
} );
</script>
<link href="css/jquery.dataTables.min.css" rel="stylesheet">
<style>
div.dataTables_wrapper {
		height: 500px;
        width: 950px;
        margin: 0 auto;
    }
</style>
<table id="example" class="table table-bordered display nowrap" style="width:100%">
<caption>PESTICIDEWISE CONSUMPTION OF IMPORTED PESTICIDES DURING 2010-11 TO 2015-16<br /></caption>
<thead>
<tr><td colspan="2" align="center">As on 09.11.2016
</td>
<td colspan="7" align="center">Unit:  M.T. (Tech. Grade)
</td>
</tr><tr><th>S. No.</th>
<th>Pesticides</th>
<th>Group</th>
<th>2010-11</th>
<th>2011-12 </th>
<th>2012-13</th>
<th>2013-14</th>
<th>2014-15</th>
<th>2015-16 (As on 09.11.2016)</th>
</tr>
</thead>
<tbody>
<tr><td colspan="9"><b>INSECTICIDES</b></td>
</tr><tr><td>1</td>
<td>Acephate</td>
<td>i</td>
<td></td>
<td>0.5</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>2</td>
<td>Acetamiprid</td>
<td>i</td>
<td>10.15</td>
<td>29.59</td>
<td>24</td>
<td>22</td>
<td>5.1</td>
<td>6.1</td>
</tr><tr><td>3</td>
<td>Aldicarb</td>
<td>i</td>
<td>5</td>
<td>6</td>
<td>6</td>
<td>6</td>
<td></td>
<td></td>
</tr><tr><td>4</td>
<td>Allethrin</td>
<td>i</td>
<td>5.76</td>
<td>10.3</td>
<td>10.6</td>
<td>16.2</td>
<td>7.5</td>
<td>6</td>
</tr><tr><td>5</td>
<td>Bita Cyfluthrin</td>
<td>i</td>
<td></td>
<td>2.1</td>
<td>5.1</td>
<td>5.7</td>
<td></td>
<td>5.2</td>
</tr><tr><td>6</td>
<td>Bita Cyfluthrin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>3.5</td>
<td></td>
</tr><tr><td>7</td>
<td>Buprofezin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
</tr><tr><td>8</td>
<td>Carbaryl</td>
<td>i</td>
<td>173.34</td>
<td>199.32</td>
<td>156.3</td>
<td>151.2</td>
<td>23.5</td>
<td>23</td>
</tr><tr><td>9</td>
<td>Carbofuran</td>
<td>i</td>
<td>287.29</td>
<td>374.58</td>
<td>266.79</td>
<td>276.44</td>
<td>16.76</td>
<td>32.83</td>
</tr><tr><td>10</td>
<td>Carbosulfan</td>
<td>i</td>
<td>9.5</td>
<td>14.33</td>
<td>10.5</td>
<td>18.6</td>
<td>12.14</td>
<td>11</td>
</tr><tr><td>11</td>
<td>Cartap Hydrochloride</td>
<td>i</td>
<td>110.2</td>
<td>268</td>
<td>150.73</td>
<td>153.77</td>
<td>28.4</td>
<td>33.33</td>
</tr><tr><td>12</td>
<td>Chlorfenvinophos </td>
<td>i</td>
<td>3</td>
<td>7.6</td>
<td>3</td>
<td>1.2</td>
<td>0.2</td>
<td>0.1</td>
</tr><tr><td>13</td>
<td>Chlorobenziliate</td>
<td>i</td>
<td></td>
<td>1</td>
<td>1</td>
<td>0.2</td>
<td>0.5</td>
<td>0.2</td>
</tr><tr><td>14</td>
<td>Chlorothalonil</td>
<td>i</td>
<td>48.04</td>
<td>43.24</td>
<td>0.9</td>
<td>10.8</td>
<td>10.3</td>
<td>8.3</td>
</tr><tr><td>15</td>
<td>Cyfluthrin</td>
<td>i</td>
<td>0.5</td>
<td>0.8</td>
<td>4.9</td>
<td>4</td>
<td>2</td>
<td>2</td>
</tr><tr><td>16</td>
<td>Cymoxanil</td>
<td>i</td>
<td></td>
<td>0.8</td>
<td>1</td>
<td>0.8</td>
<td>0.2</td>
<td>0.2</td>
</tr><tr><td>17</td>
<td>Cypermethrin</td>
<td>i</td>
<td></td>
<td>2.6</td>
<td>2.2</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>18</td>
<td>Cyphenothrin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td>0.7</td>
<td></td>
<td>2</td>
</tr><tr><td>19</td>
<td>Dazomet</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>20</td>
<td>Denprothrin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>21</td>
<td>Diazinon</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2.5</td>
</tr><tr><td>22</td>
<td>Difenconazole</td>
<td>i</td>
<td>3.93</td>
<td>5.71</td>
<td>3.85</td>
<td>4.8</td>
<td>2.5</td>
<td>3.81</td>
</tr><tr><td>23</td>
<td>Diflubenzuron</td>
<td>i</td>
<td>0.5</td>
<td>5.5</td>
<td>5</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>24</td>
<td>Dormothion</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>25</td>
<td>D-trans Allethrin</td>
<td>i</td>
<td>1.06</td>
<td>17.06</td>
<td>16</td>
<td>20</td>
<td>6</td>
<td>3</td>
</tr><tr><td>26</td>
<td>Ethepon</td>
<td>i</td>
<td>3.57</td>
<td>4.34</td>
<td>2</td>
<td>2</td>
<td></td>
<td>0.3</td>
</tr><tr><td>27</td>
<td>Ethofenprox</td>
<td>i</td>
<td>0.5</td>
<td>7.5</td>
<td>7</td>
<td>5</td>
<td></td>
<td>2</td>
</tr><tr><td>28</td>
<td>Fenobucarb(BPMC)</td>
<td>i</td>
<td>4.91</td>
<td>17</td>
<td>2.6</td>
<td>2.9</td>
<td>2.5</td>
<td>2.5</td>
</tr><tr><td>29</td>
<td>Fipronil</td>
<td>i</td>
<td>9.33</td>
<td>47.79</td>
<td>48.8</td>
<td>44.7</td>
<td>3.5</td>
<td>3.65</td>
</tr><tr><td>30</td>
<td>Flufenoxuron</td>
<td>i</td>
<td>0.4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr><tr><td>31</td>
<td>Fluvalinate</td>
<td>i</td>
<td>0.4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>32</td>
<td>Formothion</td>
<td>i</td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>33</td>
<td>Imidachloprid</td>
<td>i</td>
<td>74.22</td>
<td>141.58</td>
<td>88.05</td>
<td>98.63</td>
<td>23.97</td>
<td>29.34</td>
</tr><tr><td>34</td>
<td>Imiprothrin</td>
<td>i</td>
<td></td>
<td>2.5</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>35</td>
<td>Limda-cyahalothrin</td>
<td>i</td>
<td>42.28</td>
<td>72.46</td>
<td>53</td>
<td>67</td>
<td>18</td>
<td>17</td>
</tr><tr><td>36</td>
<td>Metsulfuron Methyl</td>
<td>i</td>
<td>2.45</td>
<td>25.2</td>
<td>27</td>
<td>27</td>
<td></td>
<td>3.25</td>
</tr><tr><td>37</td>
<td>Myclobutanil</td>
<td>i</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td></td>
<td></td>
</tr><tr><td>38</td>
<td>Oxadiargyl</td>
<td>i</td>
<td>6</td>
<td>10.89</td>
<td>5</td>
<td>9</td>
<td>3</td>
<td>3</td>
</tr><tr><td>39</td>
<td>Pendimethalene</td>
<td>i</td>
<td>73.09</td>
<td>65.1</td>
<td>41.77</td>
<td>670</td>
<td>6.25</td>
<td>0.25</td>
</tr><tr><td>40</td>
<td>Permethrin</td>
<td>i</td>
<td></td>
<td>8.5</td>
<td>8.3</td>
<td>8.2</td>
<td>4.2</td>
<td>3</td>
</tr><tr><td>41</td>
<td>Phenthoate</td>
<td>i</td>
<td>10.78</td>
<td>10.25</td>
<td>1.66</td>
<td>8.31</td>
<td>8.2</td>
<td>9.2</td>
</tr><tr><td>42</td>
<td>Primiphos-Methyle</td>
<td>i</td>
<td></td>
<td>7</td>
<td>6.7</td>
<td>5.6</td>
<td>0.5</td>
<td>1.5</td>
</tr><tr><td>43</td>
<td>Profenofos</td>
<td>i</td>
<td>267.45</td>
<td>219.63</td>
<td>130.63</td>
<td>182.27</td>
<td>61.5</td>
<td>58.7</td>
</tr><tr><td>44</td>
<td>Propargite</td>
<td>i</td>
<td>11.62</td>
<td>55.14</td>
<td>49</td>
<td>41.3</td>
<td>0.4</td>
<td>0.3</td>
</tr><tr><td>45</td>
<td>Propoxur</td>
<td>i</td>
<td>2.5</td>
<td>14.5</td>
<td>12</td>
<td>14</td>
<td>2</td>
<td>4</td>
</tr><tr><td>46</td>
<td>Propstemphos</td>
<td>i</td>
<td>0.02</td>
<td>1</td>
<td>0.9</td>
<td>1.2</td>
<td></td>
<td>1.3</td>
</tr><tr><td>47</td>
<td>Thiacloprid</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>13.7</td>
</tr><tr><td>48</td>
<td>Thiamethoxam</td>
<td>i</td>
<td>3.05</td>
<td>7.32</td>
<td>4.1</td>
<td>7.1</td>
<td>5.1</td>
<td>5.1</td>
</tr><tr><td>49</td>
<td>Thiodicarb</td>
<td>i</td>
<td>7.18</td>
<td>16.81</td>
<td>5.35</td>
<td>4.5</td>
<td>2.3</td>
<td>1.3</td>
</tr><tr><td>50</td>
<td>Thiometon</td>
<td>i</td>
<td></td>
<td></td>
<td>3.67</td>
<td>1.2</td>
<td>0.4</td>
<td>0.4</td>
</tr><tr><td>51</td>
<td>Trans Allethrin</td>
<td>i</td>
<td>2</td>
<td>1.1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>52</td>
<td>Transfluthrin</td>
<td>i</td>
<td></td>
<td></td>
<td>1.1</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>53</td>
<td>Transfluthrin</td>
<td>i</td>
<td></td>
<td></td>
<td></td>
<td>5.2</td>
<td>5.1</td>
<td>3.1</td>
</tr><tr><td>54</td>
<td>Trichlorfon</td>
<td>i</td>
<td></td>
<td>2</td>
<td>2.4</td>
<td>4.2</td>
<td>2.4</td>
<td>3.4</td>
</tr><tr><td>55</td>
<td>Trifluralin</td>
<td>i</td>
<td>1</td>
<td>2.5</td>
<td>2</td>
<td>5</td>
<td>5</td>
<td>5</td>
</tr><tr><td><b>Sub Total (Insecticide)</b></td>
<td></td>
<td></td>
<td><b>1184</b></td>
<td><b>1732</b></td>
<td><b>1173</b></td>
<td><b>1909</b></td>
<td><b>274</b></td>
<td><b>318</b></td>
</tr><tr><td colspan="9"><b><br />
FUNGICIDES</b> </td>
</tr><tr><td>56</td>
<td>Azoxystrobin</td>
<td>f</td>
<td></td>
<td>5</td>
<td>5</td>
<td>5</td>
<td></td>
<td></td>
</tr><tr><td>57</td>
<td>Benomyl</td>
<td>f</td>
<td>3</td>
<td>3.5</td>
<td>0.9</td>
<td>2.7</td>
<td>2.3</td>
<td>2.3</td>
</tr><tr><td>58</td>
<td>Bitertanol</td>
<td>f</td>
<td>3</td>
<td>3.4</td>
<td>2.6</td>
<td>0.4</td>
<td>0.2</td>
<td>0.2</td>
</tr><tr><td>59</td>
<td>Captan</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>3</td>
<td>3</td>
<td></td>
</tr><tr><td>60</td>
<td>Carbendazim</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>89</td>
<td>89</td>
<td></td>
</tr><tr><td>61</td>
<td>Carboxin</td>
<td>f</td>
<td>2</td>
<td>38.8</td>
<td>36.8</td>
<td>35.7</td>
<td>1.3</td>
<td>1.3</td>
</tr><tr><td>62</td>
<td>Copper Hydroxide</td>
<td>f</td>
<td>30.19</td>
<td>44.11</td>
<td>30.53</td>
<td>25.9</td>
<td>1.3</td>
<td>0.3</td>
</tr><tr><td>63</td>
<td>Copper Oxychloride</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>24</td>
<td>24</td>
<td></td>
</tr><tr><td>64</td>
<td>Copper Sulphate</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>19</td>
<td>19</td>
<td></td>
</tr><tr><td>65</td>
<td>Cyhalofop-N-Butyl</td>
<td>f</td>
<td>0.01</td>
<td>0.61</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>66</td>
<td>Dinocap</td>
<td>f</td>
<td>0.08</td>
<td>0.5</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>67</td>
<td>Dithianon</td>
<td>f</td>
<td>0.4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>68</td>
<td>Dodine</td>
<td>f</td>
<td>6.7</td>
<td>3.58</td>
<td>4.68</td>
<td>6.15</td>
<td></td>
<td>8.91</td>
</tr><tr><td>69</td>
<td>Ediphenphos</td>
<td>f</td>
<td>4.79</td>
<td>5.74</td>
<td>2</td>
<td>2.4</td>
<td>2.8</td>
<td>1.8</td>
</tr><tr><td>70</td>
<td>Fenarimol</td>
<td>f</td>
<td>0.5</td>
<td>0.32</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>71</td>
<td>Fenazaquin</td>
<td>f</td>
<td>0.3</td>
<td>0.32</td>
<td></td>
<td></td>
<td></td>
<td>0.1</td>
</tr><tr><td>72</td>
<td>Fenoxaprop Ethyle</td>
<td>f</td>
<td>0.5</td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td></td>
</tr><tr><td>73</td>
<td>Fosetyl-Al</td>
<td>f</td>
<td>6</td>
<td>7.3</td>
<td></td>
<td>2</td>
<td>2</td>
<td>2</td>
</tr><tr><td>74</td>
<td>Hexaconazole</td>
<td>f</td>
<td>32.6</td>
<td>83.35</td>
<td>52</td>
<td>58</td>
<td>9.8</td>
<td>7.9</td>
</tr><tr><td>75</td>
<td>Hexythiazox</td>
<td>f</td>
<td></td>
<td></td>
<td>0.05</td>
<td></td>
<td>3</td>
<td>0.3</td>
</tr><tr><td>76</td>
<td>Iprobenofos</td>
<td>f</td>
<td>5</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td></td>
<td>3</td>
</tr><tr><td>77</td>
<td>Iprodione</td>
<td>f</td>
<td></td>
<td>0.05</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>78</td>
<td>Iprovalicarb</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>3</td>
<td></td>
<td></td>
</tr><tr><td>79</td>
<td>Isoprothiolane</td>
<td>f</td>
<td>22.33</td>
<td>22.84</td>
<td>10</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>80</td>
<td>Kasugamycin</td>
<td>f</td>
<td>2</td>
<td>37</td>
<td>35</td>
<td>36</td>
<td>1</td>
<td></td>
</tr><tr><td>81</td>
<td>Kitazine</td>
<td>f</td>
<td>19.08</td>
<td>26.15</td>
<td>25.1</td>
<td>23.1</td>
<td>1.1</td>
<td>1.2</td>
</tr><tr><td>82</td>
<td>Linuron</td>
<td>f</td>
<td></td>
<td>1</td>
<td>1</td>
<td>1.5</td>
<td>0.5</td>
<td>0.5</td>
</tr><tr><td>83</td>
<td>Mancozeb</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>200</td>
<td>179</td>
<td></td>
</tr><tr><td>84</td>
<td>Metalaxyl</td>
<td>f</td>
<td>9.62</td>
<td>31.68</td>
<td>26.32</td>
<td>27.52</td>
<td>5.3</td>
<td>2.9</td>
</tr><tr><td>85</td>
<td>Metalaxyl+Mancozeb</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td></td>
</tr><tr><td>86</td>
<td>Methomyl</td>
<td>f</td>
<td>48.98</td>
<td>65.24</td>
<td>20.4</td>
<td>22.5</td>
<td></td>
<td>2.2</td>
</tr><tr><td>87</td>
<td>Novaluron</td>
<td>f</td>
<td>1</td>
<td>3</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>88</td>
<td>Organo Mercurials</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>0.7</td>
<td></td>
<td></td>
</tr><tr><td>89</td>
<td>Oxycarboxin</td>
<td>f</td>
<td></td>
<td>1.5</td>
<td>1.3</td>
<td></td>
<td>0.6</td>
<td>0.6</td>
</tr><tr><td>90</td>
<td>Penconazole</td>
<td>f</td>
<td>0.72</td>
<td>2.41</td>
<td>185.25</td>
<td>0.85</td>
<td>1.03</td>
<td>0.9</td>
</tr><tr><td>91</td>
<td>Piroxofop-Propanyl</td>
<td>f</td>
<td>10</td>
<td>10</td>
<td>8</td>
<td>10.5</td>
<td></td>
<td></td>
</tr><tr><td>92</td>
<td>Prallethrin</td>
<td>f</td>
<td>0.03</td>
<td>0.04</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>93</td>
<td>Propiconazole</td>
<td>f</td>
<td>16.89</td>
<td>65.62</td>
<td>65.58</td>
<td>65.5</td>
<td>5.19</td>
<td>6.12</td>
</tr><tr><td>94</td>
<td>Propineb</td>
<td>f</td>
<td>68.9</td>
<td>62.9</td>
<td>14.9</td>
<td>25.5</td>
<td>9.9</td>
<td>49.45</td>
</tr><tr><td>95</td>
<td>Pyraclostobin</td>
<td>f</td>
<td></td>
<td>5</td>
<td>5</td>
<td>5</td>
<td></td>
<td></td>
</tr><tr><td>96</td>
<td>Pyrazosulfaron ethyl</td>
<td>f</td>
<td></td>
<td>25</td>
<td>25</td>
<td>25</td>
<td></td>
<td></td>
</tr><tr><td>97</td>
<td>Quizalofop-P-Ethyl</td>
<td>f</td>
<td></td>
<td>15</td>
<td>15</td>
<td>22</td>
<td></td>
<td></td>
</tr><tr><td>98</td>
<td>Spinosad</td>
<td>f</td>
<td>39</td>
<td>85.5</td>
<td>75</td>
<td>71</td>
<td></td>
<td></td>
</tr><tr><td>99</td>
<td>Sulfosulfuron</td>
<td>f</td>
<td>9.24</td>
<td>39.99</td>
<td>39.17</td>
<td>39.77</td>
<td>2.07</td>
<td>5.11</td>
</tr><tr><td>100</td>
<td>Sulphur</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>144</td>
<td>144</td>
<td></td>
</tr><tr><td>101</td>
<td>Teboconazole</td>
<td>f</td>
<td>1.31</td>
<td>1.96</td>
<td>1.02</td>
<td>5.5</td>
<td>0.4</td>
<td>0.7</td>
</tr><tr><td>102</td>
<td>Thiophanate-Methyle</td>
<td>f</td>
<td>23.56</td>
<td>26.84</td>
<td>8.38</td>
<td>15.58</td>
<td>6.57</td>
<td>17.38</td>
</tr><tr><td>103</td>
<td>Thiram</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>10</td>
<td>10</td>
<td></td>
</tr><tr><td>104</td>
<td>Triadimefon</td>
<td>f</td>
<td>7</td>
<td>7.2</td>
<td>2</td>
<td>2</td>
<td></td>
<td></td>
</tr><tr><td>105</td>
<td>Tricyclazole</td>
<td>f</td>
<td>91.68</td>
<td>77.62</td>
<td>40.7</td>
<td>69.5</td>
<td>18.4</td>
<td>15.4</td>
</tr><tr><td>106</td>
<td>Zineb</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>17</td>
<td>17</td>
<td></td>
</tr><tr><td>107</td>
<td>Ziram</td>
<td>f</td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td>2</td>
<td></td>
</tr><tr><td><b>Sub Total (Fungicide)</b></td>
<td></td>
<td></td>
<td><b>466</b></td>
<td><b>813</b></td>
<td><b>742</b></td>
<td><b>1123</b></td>
<td><b>564</b></td>
<td><b>131</b></td>
</tr><tr><td colspan="9"><b>WEEDICIDES</b></td>
</tr><tr><td>108</td>
<td>2,4 D</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td>27</td>
<td>28</td>
<td></td>
</tr><tr><td>109</td>
<td>Anilophos</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td>3</td>
<td>3</td>
<td></td>
</tr><tr><td>110</td>
<td>Atrazine</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td>94</td>
<td>91</td>
<td></td>
</tr><tr><td>111</td>
<td>Benthiocarb</td>
<td>h</td>
<td>0.9</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>112</td>
<td>Butachlor</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td>69</td>
<td>65</td>
<td></td>
</tr><tr><td>113</td>
<td>Diazinon</td>
<td>h</td>
<td>2.5</td>
<td>4.57</td>
<td>4.6</td>
<td>3.5</td>
<td>2.5</td>
<td></td>
</tr><tr><td>114</td>
<td>Emamection Benzoate</td>
<td>h</td>
<td></td>
<td>4</td>
<td>3</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>115</td>
<td>Fluchloralin</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td>4</td>
<td>4</td>
<td></td>
</tr><tr><td>116</td>
<td>Glufosinate-Ammonium</td>
<td>h</td>
<td>0.5</td>
<td>2</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>117</td>
<td>Glyphosate</td>
<td>h</td>
<td>2</td>
<td></td>
<td></td>
<td>157</td>
<td>148</td>
<td></td>
</tr><tr><td>118</td>
<td>Imazathatyr</td>
<td>h</td>
<td>1</td>
<td>2.1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>119</td>
<td>Imiprothrin</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2</td>
</tr><tr><td>120</td>
<td>Indoxacarb</td>
<td>h</td>
<td>12.01</td>
<td>48.71</td>
<td>28.55</td>
<td>10</td>
<td>6</td>
<td>6.48</td>
</tr><tr><td>121</td>
<td>MCPA</td>
<td>h</td>
<td>0.2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>122</td>
<td>Metalachlor</td>
<td>h</td>
<td>2</td>
<td>9.04</td>
<td>7.5</td>
<td>2</td>
<td>2</td>
<td>2</td>
</tr><tr><td>123</td>
<td>Metoxuron</td>
<td>h</td>
<td>0.5</td>
<td></td>
<td>0.4</td>
<td>25</td>
<td>0.25</td>
<td>0.25</td>
</tr><tr><td>124</td>
<td>Metribuzin</td>
<td>h</td>
<td>22.03</td>
<td>52.6</td>
<td>26</td>
<td>38</td>
<td>11</td>
<td>7</td>
</tr><tr><td>125</td>
<td>Oxyfluorfen</td>
<td>h</td>
<td>12.01</td>
<td>14.41</td>
<td>2</td>
<td>10</td>
<td>3</td>
<td>3</td>
</tr><tr><td>126</td>
<td>Paraquat Dichloride</td>
<td>h</td>
<td></td>
<td></td>
<td></td>
<td>22</td>
<td>21</td>
<td></td>
</tr><tr><td>127</td>
<td>Pretilachlor</td>
<td>h</td>
<td>167.06</td>
<td>147.64</td>
<td>57</td>
<td>33</td>
<td>29</td>
<td>1</td>
</tr><tr><td>128</td>
<td>Siwazine</td>
<td>h</td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>129</td>
<td>Trillats</td>
<td>h</td>
<td>0.5</td>
<td></td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
</tr><tr><td><b>Sub Total (Weedicide)</b></td>
<td></td>
<td></td>
<td><b>224</b></td>
<td><b>288</b></td>
<td><b>132</b></td>
<td><b>499</b></td>
<td><b>414</b></td>
<td><b>24</b></td>
</tr><tr><td colspan="9"><b>RODENTICIDES</b></td>
</tr><tr><td>130</td>
<td>Aluminium Phosphide</td>
<td>r</td>
<td></td>
<td></td>
<td></td>
<td>8</td>
<td>8</td>
<td></td>
</tr><tr><td>131</td>
<td>Bromadiolone</td>
<td>r</td>
<td>7.64</td>
<td>11.29</td>
<td>8.07</td>
<td>13.07</td>
<td>5.07</td>
<td>2.07</td>
</tr><tr><td>132</td>
<td>Coumetetralyl</td>
<td>r</td>
<td></td>
<td></td>
<td></td>
<td>0.48</td>
<td></td>
<td>0.48</td>
</tr><tr><td>133</td>
<td>DD Mixture</td>
<td>r</td>
<td>0.64</td>
<td>7.53</td>
<td>7</td>
<td>7</td>
<td></td>
<td></td>
</tr><tr><td>134</td>
<td>Sodium Cynide</td>
<td>r</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>0.13</td>
<td>0.25</td>
</tr><tr><td>135</td>
<td>Zinc Phosphide</td>
<td>r</td>
<td></td>
<td></td>
<td></td>
<td>3</td>
<td>3</td>
<td></td>
</tr><tr><td><b>Sub Total (Rodenticides)</b></td>
<td></td>
<td></td>
<td><b>8</b></td>
<td><b>19</b></td>
<td><b>15</b></td>
<td><b>32</b></td>
<td><b>16</b></td>
<td><b>3</b></td>
</tr><tr><td colspan="9"><b>PLANT GROWTH REGULATOR</b></td>
</tr><tr><td>136</td>
<td>Alpha Napthyl Acetic Acid</td>
<td>pgr</td>
<td></td>
<td></td>
<td></td>
<td>4</td>
<td></td>
<td></td>
</tr><tr><td>137</td>
<td>Coumetetralyl</td>
<td>pgr</td>
<td>1</td>
<td>0.3</td>
<td>0.48</td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>138</td>
<td>Giberrilic acid</td>
<td>pgr</td>
<td>6.9</td>
<td>25.54</td>
<td>25.07</td>
<td>28.58</td>
<td>2</td>
<td>0.05</td>
</tr><tr><td>139</td>
<td>Hydrogen Cyanamide</td>
<td>pgr</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr><tr><td>140</td>
<td>Sodium Cyanide</td>
<td>pgr</td>
<td></td>
<td>0.15</td>
<td>0.25</td>
<td>0.35</td>
<td></td>
<td></td>
</tr><tr><td>141</td>
<td>Triacontanol</td>
<td>pgr</td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
</tr><tr><td>142</td>
<td>Validamycin</td>
<td>pgr</td>
<td>0.4</td>
<td>28.5</td>
<td>28</td>
<td>29</td>
<td></td>
<td></td>
</tr><tr><td><b>Sub total (PGR)</b></td>
<td></td>
<td></td>
<td><b>12</b></td>
<td><b>54</b></td>
<td><b>54</b></td>
<td><b>63</b></td>
<td><b>2</b></td>
<td><b>0</b></td>
</tr><tr><td><b>Total Chemical pesticides</b></td>
<td></td>
<td></td>
<td><b>1895</b></td>
<td><b>2907</b></td>
<td><b>2115</b></td>
<td><b>3625</b></td>
<td><b>1270</b></td>
<td><b>475</b></td>
</tr><tr><td colspan="9"><b>BIO-PESTICIDES</b></td>
</tr><tr><td>143</td>
<td>BacillusThurigiensis</td>
<td>bp</td>
<td>48.51</td>
<td>94.11</td>
<td>25.08</td>
<td>4</td>
<td>2</td>
<td>0.28</td>
</tr><tr><td><b>Sub total (Bio-Pesticide)</b></td>
<td></td>
<td></td>
<td><b>48.51</b></td>
<td><b>94.11</b></td>
<td><b>25.08</b></td>
<td><b>4</b></td>
<td><b>2</b></td>
<td><b>0.28</b></td>
</tr><tr><td><b>Grand total</b></td>
<td></td>
<td></td>
<td><b>1944</b></td>
<td><b>3001</b></td>
<td><b>2141</b></td>
<td><b>3629</b></td>
<td><b>1272</b></td>
<td>475</td>
</tr>
</tbody>
<tr><td colspan="9"><b>Source:</b> States/UTs, Zonal conference on inputs(PP).
</td>
</tr><tr><td colspan="9"><b>Note:-</b>h  i-  Insecticides, h– weedicides, f – Fungicides,  pgr – Plant growth regulator, bp - Biopesticide, misc- miscellaneous
</td>
</tr></table>